const ACCOUNT_STATE_BOX_SIZE = 24;
const SLOPE_CHANGE_BOX_SIZE = 16;

const ACCOUNT_POWER_SIZE = 48;
const ACCOUNT_POWER_BOX_SIZE = 1008;
const ACCOUNT_POWER_BOX_ARRAY_LEN = 21;

const TOTAL_POWER_SIZE = 48;
const TOTAL_POWER_BOX_SIZE = 1008;
const TOTAL_POWER_BOX_ARRAY_LEN = 21;

//  Boxes
const TOTAL_POWERS = Buffer.from("tp", "ascii");

export {
  ACCOUNT_STATE_BOX_SIZE,
  SLOPE_CHANGE_BOX_SIZE,
  ACCOUNT_POWER_SIZE,
  ACCOUNT_POWER_BOX_SIZE,
  ACCOUNT_POWER_BOX_ARRAY_LEN,
  TOTAL_POWER_BOX_ARRAY_LEN,
  TOTAL_POWER_BOX_SIZE,
  TOTAL_POWER_SIZE,
  TOTAL_POWERS
};
